[rke2_servers]
# RKE2 Control Plane (Master) Nodes
# terraform output의 ip를 여기에 매핑합니다.
rke2-server-01 ansible_host=192.168.4.11 ansible_user=ncloud

[rke2_agents]
# RKE2 Data Plane (Worker) Nodes
# ASG로 프로비저닝된 에이전트 또는 정적 에이전트를 정의합니다.

[rke2_cluster:children]
rke2_servers
rke2_agents

[all:vars]
ansible_ssh_common_args='-o ProxyCommand="ssh -W %h:%p -q ncloud@<team1-bastion-public-ip>"'
