apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: koslink-backend-app
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://github.com/koscom-team01/kosops.git'
    targetRevision: HEAD
    path: gitops/charts/generic-app
    helm:
      values: |
        replicaCount: 2
        image:
          repository: harbor.hwangonjang.com/library/koslink-backend
          tag: 1
          pullPolicy: Always
        service:
          type: ClusterIP
          port: 8080
        ingress:
          enabled: true
          className: nginx
          annotations:
            ingress.kubernetes.io/ssl-redirect: "false"
            nginx.ingress.kubernetes.io/ssl-redirect: "false"
          hosts:
            - host: koslink-api.hwangonjang.com
              paths:
                - path: /
                  pathType: Prefix
        env:
          - name: SPRING_DATASOURCE_URL
            value: "jdbc:postgresql://postgres-service:5432/koscomdb"
          - name: SPRING_DATASOURCE_USERNAME
            value: "admin"
          - name: SPRING_DATASOURCE_PASSWORD
            value: "adminpassword"
          - name: AI_SERVICE_URL
            value: "http://koslink-ai-app:8000"
          - name: CORS_ALLOWED_ORIGINS
            value: "https://koslink.hwangonjang.com,http://koslink.hwangonjang.com,https://koslink-ai.hwangonjang.com,https://team1.hwangonjang.com,http://localhost:5173,https://koslink-api.hwangonjang.com"
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: koslink
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
